function plotlatex(t,y,xlab,ylab)

width = 5;
height = 5;
x0 = 0;
y0 = 0;
figure('Units','inches',...
    'Position',[x0 y0 width height],...
    'PaperPositionMode','auto');
    
semilogy(t,y,'LineWidth',2)
hold on
semilogy(0.2500,0.4E-3,'ob')
hold off

%axis([0 1 1E-4 1E-1])
grid on
set(gca,...
    'Units','normalized',...
    'XTick',0:0.2:1,...
    'YTick',[1E-4,1E-3,1E-2,1E-1],...
    'Position',[.15 .2 .75 .7],...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times',...
    'Color','none',...
    'GridLineStyle','--');
 
ylabel(ylab,...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times')
xlabel(xlab,...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
% legend({'$y=\sin(t)$'},...
%     'FontUnits','points',...
%     'interpreter','latex',...
%     'FontSize',12,...
%     'FontName','Times',...
%     'Location','NorthEast')
% title('Sinusoidal function',...
%     'FontUnits','points',...
%     'FontWeight','normal',...
%     'FontSize',7,...
%     'FontName','Times')
print(strcat(ylab,'.png'),'-dpng')
%print -depsc2 myplot.eps

